server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/custom_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      root: INFO


  jackson:
    date-format: yyyy-MM-dd


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER




# yml dosyası tercih etme sebebim properties biçimine göre daha kullanışlı olmasıdır.
#(key-value / dizi /derinlik acısından)
#projelerde genel olarak bu bicimi tercih ediyorum. Bu projede de terihim oldu.